name: angularforce
description: A sample web application with dart force
dependencies:
  browser: any
  force: 
    git: 
      url: git://github.com/ForceUniverse/dart-force.git
      ref: experimental
  angular: 1.0.0
  bigcargo: 
       git: git://github.com/ForceUniverse/bigcargo
  cargo: any
  google_oauth2_client: ">=0.4.1 <0.5.0"
transformers:
- angular
